steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - atualiza-dados-nubank
  - --region=us-central1
  - --source=https://https://source.cloud.google.com/finances-314506/github_alex-rsiqueira_finance-repo/+/main:GCP/cloud-function/atualiza-dados-nubank/
options:
  logging: NONE